extends: default
rules:
  line-length:
    max: 200
    level: warning

  truthy:
    allowed-values: ["true", "false", "yes", "no"]

  indentation:
    spaces: 2
    indent-sequences: consistent
  comments: 
    min-spaces-from-content: 1

  document-start: disable
  
ignore:
  infra/cloudformation/*.yaml